#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/mechuser/neuron_mpi/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/mechuser/neuron_mpi/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/mechuser/github/parallel/x86_64/.libs/libnrnmech.so" "$@"
